# Generated by Django 5.0.14 on 2025-04-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
