# Generated by Django 5.0.14 on 2025-04-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recruiter_cover_recruiter_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='jobseeker_images/'),
        ),
    ]
