# Generated by Django 5.0.14 on 2025-04-28 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_recruiter_cover_alter_recruiter_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
